#!/usr/bin/env python3
"""
metatool.py - inspect and strip metadata in .docx and .pdf files.

Scripted:
    python3 metatool.py check file1.docx dir/
    python3 metatool.py check --json file1.docx
    python3 metatool.py clean file1.docx --out-dir cleaned/ --set-author "Name"

Interactive (no subcommand, or -i):
    python3 metatool.py
"""

import sys
import io
import contextlib
import json
import shlex
import random
import zipfile
import argparse
import xml.etree.ElementTree as ET
from pathlib import Path
from datetime import datetime, timezone, timedelta

SUSPICIOUS_CREATOR_TOOLS = [
    "python-docx", "python-pptx", "openpyxl", "reportlab", "fpdf",
    "libreoffice", "pandoc", "weasyprint", "wkhtmltopdf", "chromium",
    "headless", "puppeteer", "playwright",
]

CORE_NS = {
    "cp": "http://schemas.openxmlformats.org/package/2006/metadata/core-properties",
    "dc": "http://purl.org/dc/elements/1.1/",
    "dcterms": "http://purl.org/dc/terms/",
}
APP_NS = {
    "ep": "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties",
}

CORE_XML_TEMPLATE = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    '<cp:coreProperties '
    'xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" '
    'xmlns:dc="http://purl.org/dc/elements/1.1/" '
    'xmlns:dcterms="http://purl.org/dc/terms/" '
    'xmlns:dcmitype="http://purl.org/dc/dcmitype/" '
    'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
    '<dc:title></dc:title><dc:subject></dc:subject>'
    '<dc:creator>{author}</dc:creator><cp:keywords></cp:keywords>'
    '<dc:description></dc:description>'
    '<cp:lastModifiedBy>{author}</cp:lastModifiedBy>'
    '<cp:revision>{revision}</cp:revision>'
    '<dcterms:created xsi:type="dcterms:W3CDTF">{created}</dcterms:created>'
    '<dcterms:modified xsi:type="dcterms:W3CDTF">{modified}</dcterms:modified>'
    '<cp:category></cp:category></cp:coreProperties>'
)

APP_XML_STRIP_TAGS = ["Manager", "Company", "Template"]


# --------------------------------------------------------------------------
# shared
# --------------------------------------------------------------------------

def flag(findings, level, message):
    findings.append({"level": level, "message": message})


def text_of(root, path, ns):
    el = root.find(path, ns)
    return el.text if el is not None and el.text else ""


def collect_files(paths):
    collected = []
    for p in paths:
        path = Path(p)
        if path.is_dir():
            for pat in ("*.docx", "*.pdf"):
                collected.extend(f for f in sorted(path.rglob(pat)) if "results" not in f.parts)
        else:
            collected.append(path)
    return collected


# --------------------------------------------------------------------------
# check
# --------------------------------------------------------------------------

def check_docx(path):
    findings = []
    props = {}
    with zipfile.ZipFile(path) as z:
        names = z.namelist()

        if "docProps/core.xml" in names:
            root = ET.fromstring(z.read("docProps/core.xml"))
            props["creator"] = text_of(root, "dc:creator", CORE_NS)
            props["description"] = text_of(root, "dc:description", CORE_NS)
            props["lastModifiedBy"] = text_of(root, "cp:lastModifiedBy", CORE_NS)
            props["revision"] = text_of(root, "cp:revision", CORE_NS)
            props["created"] = text_of(root, "dcterms:created", CORE_NS)
            props["modified"] = text_of(root, "dcterms:modified", CORE_NS)
        else:
            flag(findings, "warn", "docProps/core.xml missing (unusual for a real Word file).")

        if "docProps/app.xml" in names:
            root = ET.fromstring(z.read("docProps/app.xml"))
            props["application"] = text_of(root, "ep:Application", APP_NS)
            props["totalTime"] = text_of(root, "ep:TotalTime", APP_NS)
            props["pages"] = text_of(root, "ep:Pages", APP_NS)
            props["words"] = text_of(root, "ep:Words", APP_NS)

    creator = props.get("creator", "")
    description = props.get("description", "")
    combined = f"{creator} {description}".lower()

    for tool in SUSPICIOUS_CREATOR_TOOLS:
        if tool in combined:
            flag(findings, "high",
                 f"Creator/description references '{tool}' — file was likely generated by a script, "
                 f"not typed directly in an office app.")
            break

    if props.get("created") == "2013-12-23T23:15:00Z":
        flag(findings, "high",
             "created date matches python-docx's default template timestamp "
             "(2013-12-23T23:15:00Z), not a real authoring date.")

    if props.get("creator") and props.get("lastModifiedBy"):
        if props["creator"].strip().lower() in ("python-docx", "unknown", "") and \
           props["lastModifiedBy"].strip() and props["creator"] != props["lastModifiedBy"]:
            flag(findings, "med",
                 f"Original creator ('{props['creator']}') differs from lastModifiedBy "
                 f"('{props['lastModifiedBy']}') — file was authored by one identity/tool "
                 f"then opened and saved under another.")

    try:
        revision = int(props.get("revision", "0") or 0)
        total_time = int(props.get("totalTime", "0") or 0)
        pages = int(props.get("pages", "0") or 0)
        if pages >= 10 and revision <= 5 and total_time < pages * 2:
            flag(findings, "med",
                 f"Only {revision} save(s) and {total_time} minute(s) of editing time for "
                 f"a {pages}-page document — short for content authored entirely by hand.")
    except ValueError:
        pass

    return props, findings


def check_pdf(path):
    import pikepdf
    findings = []
    props = {}

    with pikepdf.open(path) as pdf:
        docinfo = pdf.docinfo
        for key in ("/Author", "/Creator", "/Producer", "/CreationDate", "/ModDate"):
            if key in docinfo:
                props[key.strip("/")] = str(docinfo[key])

        if "/Metadata" in pdf.Root:
            raw = pdf.Root.Metadata.read_bytes()
            props["xmp_raw"] = raw.decode("utf-8", errors="replace")

    combined = " ".join(str(v) for v in props.values()).lower()
    for tool in SUSPICIOUS_CREATOR_TOOLS:
        if tool in combined:
            flag(findings, "high",
                 f"Metadata references '{tool}' — PDF content was likely produced or "
                 f"assembled by a script rather than typed and exported manually.")
            break

    author = props.get("Author", "")
    creator = props.get("Creator", "")
    if author and creator and author.lower() != creator.lower():
        if any(tool in author.lower() for tool in SUSPICIOUS_CREATOR_TOOLS):
            flag(findings, "med",
                 f"Author field ('{author}') is a software library name, while Creator "
                 f"('{creator}') is an office app — consistent with generate-then-export flow.")

    creation = props.get("CreationDate", "")
    mod = props.get("ModDate", "")
    if creation and creation == mod:
        flag(findings, "low",
             "CreationDate equals ModDate exactly — consistent with a one-shot "
             "generate-and-export, though also normal for a simple manual export.")

    return props, findings


def analyze(path_str: str) -> dict:
    path = Path(path_str)
    if not path.exists():
        return {"file": path_str, "error": "file not found", "properties": {}, "findings": []}

    ext = path.suffix.lower()
    try:
        if ext == ".docx":
            props, findings = check_docx(path)
        elif ext == ".pdf":
            props, findings = check_pdf(path)
        else:
            return {"file": str(path), "error": f"unsupported extension '{ext}'", "properties": {}, "findings": []}
    except Exception as e:
        return {"file": str(path), "error": str(e), "properties": {}, "findings": []}

    return {"file": str(path), "properties": props, "findings": findings}


def print_human(result):
    print(f"\n=== {result['file']} ===")
    if "error" in result:
        print(f"  ERROR: {result['error']}")
        return

    for k, v in result["properties"].items():
        if k == "xmp_raw":
            continue
        print(f"  {k}: {v}")

    findings = result["findings"]
    if not findings:
        print("  No suspicious signals found.")
        return

    print("  --- flags ---")
    order = {"high": 0, "med": 1, "low": 2, "warn": 3}
    for f in sorted(findings, key=lambda x: order.get(x["level"], 9)):
        print(f"  [{f['level'].upper()}] {f['message']}")


# --------------------------------------------------------------------------
# clean
# --------------------------------------------------------------------------

def strip_tag_content(xml_text, tag, replacement=""):
    open_tag = f"<{tag}>"
    close_tag = f"</{tag}>"
    start = xml_text.find(open_tag)
    if start == -1:
        return xml_text
    end = xml_text.find(close_tag, start)
    if end == -1:
        return xml_text
    end += len(close_tag)
    return xml_text[:start] + f"{open_tag}{replacement}{close_tag}" + xml_text[end:]


def clean_docx(src, dst, author):
    now = datetime.now(timezone.utc)
    modified = now.strftime("%Y-%m-%dT%H:%M:%SZ")
    created = (now - timedelta(minutes=random.randint(5, 480))).strftime("%Y-%m-%dT%H:%M:%SZ")
    revision = random.randint(2, 12)
    core_xml = CORE_XML_TEMPLATE.format(
        author=author, revision=revision, created=created, modified=modified
    ).encode("utf-8")

    with zipfile.ZipFile(src, "r") as zin:
        names = zin.namelist()
        with zipfile.ZipFile(dst, "w", zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                data = zin.read(item.filename)

                if item.filename == "docProps/core.xml":
                    data = core_xml
                elif item.filename == "docProps/app.xml":
                    text = data.decode("utf-8", errors="replace")
                    for tag in APP_XML_STRIP_TAGS:
                        text = strip_tag_content(text, tag)
                    text = strip_tag_content(text, "TotalTime", replacement="0")
                    data = text.encode("utf-8")
                elif item.filename == "docProps/custom.xml":
                    continue

                zout.writestr(item, data)

    if "docProps/core.xml" not in names:
        with zipfile.ZipFile(dst, "a", zipfile.ZIP_DEFLATED) as zout:
            zout.writestr("docProps/core.xml", core_xml)


def clean_pdf(src, dst, author):
    import pikepdf

    with pikepdf.open(src) as pdf:
        for key in list(pdf.docinfo.keys()):
            del pdf.docinfo[key]

        if author:
            pdf.docinfo["/Author"] = author

        if "/Metadata" in pdf.Root:
            del pdf.Root.Metadata

        pdf.save(dst)


def process_file(path_str, out_dir, author):
    path = Path(path_str)
    if not path.exists():
        print(f"  ERROR: {path} not found")
        return None

    ext = path.suffix.lower()
    if ext not in (".docx", ".pdf"):
        print(f"  SKIP: {path} — unsupported extension '{ext}'")

    out_dir = out_dir or path.parent / "results"
    out_dir.mkdir(parents=True, exist_ok=True)
    dst = out_dir / path.name
    n = 1
    while dst.exists():
        dst = out_dir / f"{path.stem}({n}){path.suffix}"
        n += 1

    try:
        if ext == ".docx":
            clean_docx(path, dst, author or "Author")
        else:
            clean_pdf(path, dst, author)
        print(f"  OK: {path} -> {dst}")
    except Exception as e:
        print(f"  ERROR processing {path}: {e}")


# --------------------------------------------------------------------------
# runners
# --------------------------------------------------------------------------

def run_check(paths, as_json=False):
    targets = collect_files(paths)
    if not targets:
        print("No .docx or .pdf files found.")
        return
    results = [analyze(str(f)) for f in targets]
    if as_json:
        print(json.dumps(results, indent=2, ensure_ascii=False))
    else:
        for r in results:
            print_human(r)
        print()


def run_clean(paths, out_dir=None, author=None):
    targets = collect_files(paths)
    if not targets:
        print("No .docx or .pdf files found.")
        return
    print("Cleaning files:")
    for f in targets:
        process_file(str(f), out_dir, author)



def interactive():
    try:
        from textual.app import App, ComposeResult
        from textual.containers import Horizontal, Vertical
        from textual.widgets import Input, Button, RichLog, Tree
        from textual import on
    except ImportError:
        print("Install textual for the TUI: pip install --user --break-system-packages textual")
        return

    class MetatoolApp(App):
        CSS = """
        #log { height: 10; border: round $accent; }
        #tree { height: 1fr; border: round $accent; }
        #bar { height: 3; }
        #paths { width: 1fr; }
        #author_in { width: 1fr; }
        """

        def compose(self) -> ComposeResult:
            with Vertical():
                yield Tree("results", id="tree")
                with Horizontal(id="bar"):
                    yield Input(placeholder="paths (blank = files/)", id="paths")
                    yield Input(placeholder="author (blank = generic)", id="author_in")
                    yield Button("Check", id="check")
                    yield Button("Clean", id="clean")
                    yield Button("Quit", id="quit")

        def on_mount(self) -> None:
            self.query_one("#paths", Input).focus()

        def _paths(self):
            raw = self.query_one("#paths", Input).value.strip()
            return shlex.split(raw) if raw else ["files"]

        def _author(self):
            return self.query_one("#author_in", Input).value.strip() or None

        @on(Button.Pressed, "#check")
        def do_check(self) -> None:
            log = self.query_one("#log", RichLog)
            tree = self.query_one("#tree", Tree)
            tree.clear()
            targets = collect_files(self._paths())
            if not targets:
                log.write("[yellow]no supported files found[/yellow]")
                return
            for f in targets:
                res = analyze(str(f))
                fname = Path(res["file"]).name
                if "error" in res:
                    node = tree.root.add(f"[red]{fname}[/red] — {res['error']}")
                    continue
                n_props = len(res["properties"])
                n_high = sum(1 for x in res["findings"] if x["level"] == "high")
                node = tree.root.add(
                    f"[bold]{fname}[/bold] ({n_props} fields, {n_high} high flags)",
                    expand=False,
                )
                for k, v in res["properties"].items():
                    val = (v[:200] + "…") if k == "xmp_raw" and len(v) > 200 else v
                    node.add_leaf(f"{k}: {val}")
                if res["findings"]:
                    fnode = node.add("findings")
                    order = {"high": 0, "med": 1, "low": 2, "warn": 3}
                    for x in sorted(res["findings"], key=lambda y: order.get(y["level"], 9)):
                        fnode.add_leaf(f"[{x['level'].upper()}] {x['message']}")
                else:
                    node.add_leaf("[green]no suspicious signals[/green]")
            log.write(f"[bold]check[/bold] {len(targets)} file(s) — click file rows to expand/collapse")

        @on(Button.Pressed, "#clean")
        def do_clean(self) -> None:
            log = self.query_one("#log", RichLog)
            paths, author = self._paths(), self._author()
            log.write(f"[bold]clean[/bold] {paths} author={author!r}")
            buf = io.StringIO()
            with contextlib.redirect_stdout(buf):
                run_clean(paths, None, author)
            log.write(buf.getvalue() or "(no output)")

        @on(Button.Pressed, "#quit")
        def do_quit(self) -> None:
            self.exit()

    MetatoolApp().run()


def main():
    parser = argparse.ArgumentParser(
        prog="metatool",
        description="Inspect and strip metadata in .docx/.pdf files.",
    )
    parser.add_argument("-i", "--interactive", action="store_true",
                        help="force interactive mode")
    sub = parser.add_subparsers(dest="cmd")

    c = sub.add_parser("check", help="scan for suspicious metadata")
    c.add_argument("files", nargs="*", default=["files"],
                   help=".docx/.pdf files or directories (default: files/)")
    c.add_argument("--json", action="store_true", help="JSON output")

    cl = sub.add_parser("clean", help="strip metadata")
    cl.add_argument("files", nargs="*", default=["files"],
                    help=".docx/.pdf files or directories (default: files/)")
    cl.add_argument("--out-dir", type=Path, default=None,
                    help="write cleaned files here (default: _cleaned alongside originals)")
    cl.add_argument("--set-author", type=str, default=None,
                    help="author to set instead of blanking")

    args = parser.parse_args()

    if args.interactive or args.cmd is None:
        interactive()
    elif args.cmd == "check":
        run_check(args.files, args.json)
    else:
        run_clean(args.files, args.out_dir, args.set_author)


if __name__ == "__main__":
    main()
