from __future__ import annotations

import xml.etree.ElementTree as element_tree
import zipfile
from pathlib import Path

from metatool.models import SanitizationOptions
from metatool.sanitizers.ooxml import OOXMLSanitizer

CORE_NAMESPACE = "http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
DC_NAMESPACE = "http://purl.org/dc/elements/1.1/"


def test_privacy_profile_removes_python_docx_description(tmp_path: Path) -> None:
    source_path = tmp_path / "report.docx"
    destination_path = tmp_path / "report-clean.docx"
    core_properties = f"""<cp:coreProperties xmlns:cp="{CORE_NAMESPACE}" xmlns:dc="{DC_NAMESPACE}">
      <dc:title>Quarterly report</dc:title>
      <dc:description>Generated by python-docx</dc:description>
      <dc:creator>Alice</dc:creator>
    </cp:coreProperties>"""
    with zipfile.ZipFile(source_path, "w") as package_archive:
        package_archive.writestr("[Content_Types].xml", "<Types />")
        package_archive.writestr("docProps/core.xml", core_properties)

    OOXMLSanitizer().sanitize(source_path, destination_path, SanitizationOptions(profile="privacy"))

    with zipfile.ZipFile(destination_path) as package_archive:
        core_properties_root = element_tree.fromstring(package_archive.read("docProps/core.xml"))
    assert core_properties_root.find(f"{{{DC_NAMESPACE}}}description") is None
