from __future__ import annotations

from pathlib import Path

from docx import Document

from metatool.models import SanitizationOptions
from metatool.sanitizers.ooxml import OOXMLSanitizer


def test_sanitized_real_docx_reopens_with_python_docx(tmp_path: Path) -> None:
    source_path = tmp_path / "source.docx"
    destination_path = tmp_path / "clean.docx"
    document = Document()
    document.add_heading("Metadata round trip", level=1)
    document.add_paragraph("This document must remain readable after sanitization.")
    document.core_properties.creator = "Alice"
    document.core_properties.last_modified_by = "Bob"
    document.core_properties.description = "Generated by python-docx"
    document.save(source_path)

    OOXMLSanitizer().sanitize(source_path, destination_path, SanitizationOptions(profile="privacy"))

    reopened = Document(destination_path)
    assert reopened.paragraphs[0].text == "Metadata round trip"
    assert reopened.paragraphs[1].text.startswith("This document must remain")
