from __future__ import annotations

import xml.etree.ElementTree as element_tree
import zipfile
from pathlib import Path

from metatool.models import SanitizationOptions
from metatool.sanitizers.ooxml import OOXMLSanitizer

CORE_NAMESPACE = "http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
DC_NAMESPACE = "http://purl.org/dc/elements/1.1/"
CP_NAMESPACE = "http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
EXTENDED_NAMESPACE = "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"


def _write_document(document_path: Path) -> None:
    core_properties = f"""<cp:coreProperties xmlns:cp="{CORE_NAMESPACE}" xmlns:dc="{DC_NAMESPACE}">
      <dc:title>Quarterly report</dc:title>
      <dc:description>Generated by python-docx</dc:description>
      <dc:creator>Alice</dc:creator>
      <cp:lastModifiedBy>Bob</cp:lastModifiedBy>
      <cp:keywords>finance</cp:keywords>
    </cp:coreProperties>"""
    extended_properties = f"""<Properties xmlns="{EXTENDED_NAMESPACE}">
      <Application>Microsoft Office Word</Application>
      <Company>Example Corp</Company>
      <Manager>Pat</Manager>
    </Properties>"""
    with zipfile.ZipFile(document_path, "w") as package_archive:
        package_archive.writestr("[Content_Types].xml", "<Types />")
        package_archive.writestr("docProps/core.xml", core_properties)
        package_archive.writestr("docProps/app.xml", extended_properties)


def _read_part(document_path: Path, part_name: str) -> element_tree.Element:
    with zipfile.ZipFile(document_path) as package_archive:
        return element_tree.fromstring(package_archive.read(part_name))


def test_privacy_profile_removes_description_and_application(tmp_path: Path) -> None:
    source_path = tmp_path / "report.docx"
    destination_path = tmp_path / "privacy.docx"
    _write_document(source_path)

    OOXMLSanitizer().sanitize(source_path, destination_path, SanitizationOptions(profile="privacy"))

    core_properties = _read_part(destination_path, "docProps/core.xml")
    extended_properties = _read_part(destination_path, "docProps/app.xml")
    assert core_properties.find(f"{{{DC_NAMESPACE}}}description") is None
    assert extended_properties.find(f"{{{EXTENDED_NAMESPACE}}}Application") is None


def test_author_profile_does_not_put_author_in_description(tmp_path: Path) -> None:
    source_path = tmp_path / "report.docx"
    destination_path = tmp_path / "author.docx"
    _write_document(source_path)

    OOXMLSanitizer().sanitize(
        source_path,
        destination_path,
        SanitizationOptions(profile="author", author="Jane Doe"),
    )

    core_properties = _read_part(destination_path, "docProps/core.xml")
    extended_properties = _read_part(destination_path, "docProps/app.xml")
    assert core_properties.find(f"{{{DC_NAMESPACE}}}creator").text == "Jane Doe"
    assert core_properties.find(f"{{{CP_NAMESPACE}}}lastModifiedBy").text == "Jane Doe"
    assert core_properties.find(f"{{{DC_NAMESPACE}}}description") is None
    assert extended_properties.find(f"{{{EXTENDED_NAMESPACE}}}Application") is None
